### ISSUE TITLE
On example.sage, S234.compute_homology() is raising an exception

### ISSUE THREAD

**Issue by viorato** [sucharit/hf-hat#1]
On the example.sage file, I have noticed that you enclosed the function `compute_homology()` on a `try except` . So, I decided to print the exception message in case one is being raised, so I changed the code to:

```
try:
    S234.generate_complexes()
    S234.compute_homology()
except Exception as e:
    print "Error computing Homology: {0}". format(e)
    pass
```

After the execution, the following exception was raise: "Not enough data to generate complexes"

This is happening when I load example.sage into sage. Am I doing something wrong? Do I need to do something else? Do you have another Heegaard Diagram example where `compute_homology()` runs without errors?

Thanks for sharing your code.

Regards,
Jesus

**Comment by sucharit** [comment]
generate_complexes() creates a chain complex (think of it as a matrix), and then compute_homology() computes its homology (think of it as computing the kernel of the matrix). However, the program in general cannot compute the entire chain complex (that is, it doesn't know all the matrix entries); in fact, there is no general algorithm to do it. So when the program cannot compute all the entries, it won't be able to compute the homology, and you get the exception "Not enough data to generate complexes". You can also see this in the pretty_print() function. Red lines mean that the program knows there is a differential, and blue lines mean that that the program doesn't know that entry.

In the example.sage file, there are 4 Heegaard diagrams, S234, S237, trefoil, and L31. Of these 4, the program will only be able to compute the entire chain complex for trefoil, and then compute its homology. This program is mainly meant for analyzing Heegaard diagrams by hand: the program computes all the differentials that it can, and then humans have to analyze the matrix entries that the program couldn't figure out.

There is a similar story with the compute_mc_homology() function.

**Comment by viorato** [comment]
I got the wrong idea that the program was capable to compute the homology for any diagram. It is a nice and helpful code any way.

Thanks for your reply,
